---
- when: 
    - (docker_engine | default(false)) != false
  name: config docker-ce
  block:
    - name: ensure '/etc/docker'
      file: state=directory recurse=yes path=/etc/docker
    - name: config /etc/docker/daemon.json
      vars:
        engine_effective_config: "{{ engine_default_config | default({},true) | combine( engine_config | default({},true)) }}"
        npc_labels: "{{ group_names | default([]) | map('regex_replace', '^(.+)$', 'npc.group.\\1=Y')|list + ['npc.name='+inventory_hostname ] }}"      
        engine_labels: "{{ npc_labels + (engine_effective_config.labels | default([],true)) }}"
      copy: 
        dest: /etc/docker/daemon.json
        content: "{{ engine_effective_config | combine( dict(labels=engine_labels) ) | to_json }}"
      notify: 
        - reload docker config

- when: 
    - (docker_engine | default(false)) != false
    - not (
        ansible_local is defined and 
        ansible_local.npc_docker is defined 
        and ansible_local.npc_docker.is_installed 
        and ansible_local.npc_docker.version.startswith( 
          docker_engine.version | default(docker_engine|string|ternary(docker_engine, ""), true)
        )
      )
  include: docker_engine.yml

- when:
    - (docker_swarm | default(false)) != false
    # run once
    - inventory_hostname == ansible_play_hosts[0]
  include: docker_swarm.yml
  
- when: 
    - (docker_swarm | default(false)) != false
    - inventory_hostname == ansible_play_hosts[0]

    - (docker_swarm_managers | length) > 0
    - (docker_swarm | default({})).stack is defined
  include: docker_swarm.stacks.yml
    